### ISSUE TITLE
Doc.

### ISSUE THREAD

**Issue by sultanassi95** [FACG4/PWD-helper-from-the-very-beginning-#16]
Hey there..

- [x] Can we replace `Don't Know` in answer boxes on the template with `__` or we can leave it empty instead. :pray: 
- [x] Can we try removing the empty pages when they are empty? we don't want our client wasting some papers when printing the report or something :scream:

**Comment by sallamTanna** [comment]
Hi @sultanassi95  , at first, "Don't know" answer was an empty space, BUT, yesterday in presentation, Ahmed and Ghada told us that it is better to be "do not know" if the user did not answer the question. We do not any field to be empty!!

**Comment by IsraaMoqbel** [comment]
regarding the empty pages, I tried to add page breaks after each section to avoid making empty spaces but it was useless!!! :weary:

**Comment by sultanassi95** [comment]
@sallamTanna maybe we can do `__` or `No` instead of `don't know`
I think, as an engineer, it's not acceptable to have an answer such like `don't know` :smile: 
I will check with Ghada and Ahmed on that.

**Comment by sultanassi95** [comment]
@IsraaMoqbel I will check that.

**Comment by sultanassi95** [comment]
@IsraaMoqbel 

We can do this.

for example. section one comments and Photos, for now it's like:
```
Comments:
{#sectionATextarea}{sectionATextarea}{/sectionATextarea}

Photos of Section A :
{#img1Asize}
{%img1A}
{/img1Asize}
{#img2Asize}
{%img2A}
{/img2Asize}
```

but, when there is no comments or photos, then we will have empty spaces instead..
we can add else conditions.
for Example, if there is no comments print: `No comments were added by the engineer.`
if there are no photos: `No photos were provided by the engineer.`

Also.. before we start showing the comments and photos.
we can add a head line that indicates what these comments and photos for.
for example, section one's headline is `APROACH AND ENTRANCE `
Then, we can do this:

```
APROACH AND ENTRANCE Comments and Photos:

Comments:
{#sectionATextarea}{sectionATextarea}{/sectionATextarea}

Photos of Section A :
{#img1Asize}
{%img1A}
{/img1Asize}
{#img2Asize}
{%img2A}
{/img2Asize}
```

Another thing to add.
go to page 6 in the template. we should move the comment and photos part to a new page.
and we should do that for each section.


One last thing, page 16 is all white spaces and new white lines, remove it.
That's for comments and photos part in the template..
