### ISSUE TITLE
Finish Form Features.

### ISSUE THREAD

**Issue by sultanassi95** [FACG4/PWD-helper-from-the-very-beginning-#5]
# V1.1

- [x] add recommendation parts #7 

# V1

# Must:
- [x] submit and analysis.
- - Description: a user must be able to submit the form and see analytics.
- [x] export to `doc`.
- - Description: a user must be able to export the form with its images after submit.

# Sidery:
- [x] Good template. (contains the images)

## Deadline: 25th. June. 4:00 PM.

**Comment by IsraaMoqbel** [comment]
I'm exporting the form not the analysis! :thinking:

**Comment by sultanassi95** [comment]
selly mistake.
:sweat_smile:
